services:
  api:
    build:
      context: ./backend
      dockerfile: ./src/Avvo.API/Dockerfile
    container_name: nuc_api
    ports:
      - "8080:8080" # acesso externo
    depends_on:
      - db
